### PR TITLE
Update oed code snippets (everything except 4a)

### PR DESCRIPTION
**Pull request by jayelm**
Just want to confirm before I merge:

There are slight floating point errors in 1b (like, the last decimal point is off).

Fig 2b and 3b have different values because of the switch from `randomInteger(n)` to `randomInteger(n + 1)`.

No differences between figures 2a and 4b.

[fig1b.diff.txt](https://github.com/mhtess/oed/files/348923/fig1b.diff.txt)
[fig2b.diff.txt](https://github.com/mhtess/oed/files/348924/fig2b.diff.txt)
[fig3.diff.txt](https://github.com/mhtess/oed/files/348925/fig3.diff.txt)

### CODE REVIEW

**Comment by jayelm** [comment]
Also, I only looked at a couple of the differences in figures 2b and 3 earlier. Now checking again it appears as though some of the EIG differences are more substantial.

**Comment by longouyang** [comment]
Summarizing an in-person discussion: the plan is to check by make the figures before and after the change and do a visual diff to see if anything's weird.

**Comment by jayelm** [comment]
Check 2b10eaf62cfe1952d4eb19e27112da772204b04f. Points have shifted but nothing seems to be amiss. I'll clean up the commit history when we're good to go.

**Comment by jayelm** [comment]
Note here that **added** are the plots after the bugfix. Interestingly, my original jsons (before the bugfix) differed with long with very minor floating point/rounding errors, like:

```
252c252
<   "aig": 0.26748718236303415
---
>   "aig": 0.2674871823630341
279c279
<   "eig": 0.28189641508329777,
---
>   "eig": 0.2818964150832977,
293c293
<   "eig": 0.296696403572835,
---
>   "eig": 0.29669640357283494,
```

I'm confused as to why that would happen, but the differences seem to be negligible, so I'm ignoring it for now. But as a result, the old plots' r-squared values differ from the paper submission by .01 in the two panels on the right.

**Comment by jayelm** [comment]
Actually, hold on for a second, some trickery going on here.

**Comment by jayelm** [comment]
Okay: as it turns out, the old repo before the bugfix produced figures that were slightly different from the figures in the submission. After the bugfix, the JSON files produce exactly the figures in the submission. So it seems like the repo code was not used to produce the submission figures, if anyone can explain that.

So, the only differences are the floating point/rounding things in figure 1b.

**Comment by longouyang** [comment]
> So it seems like the repo code was not used to produce the submission figures, if anyone can explain that.

Yeah, we actually made the figures in non-reproducible way while rushing to meet the NIPS deadline. I made the reproducible Makefile stuff after we submitted. Thanks a bunch for figuring all this out.

So things work okay with the new `M`, `X`, and `Y` interface?

**Comment by jayelm** [comment]
I've tested everything except Figure 4a and it works. We'd need to use the server to test 4a.

**Comment by longouyang** [comment]
Okay, I'll do those runs this weekend.

**Pull request merged**
